INSERT INTO component_example (id_component, attr, "style") VALUES
    ((select id from component where  "name" = 'table'), NULL, NULL),
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'container'), NULL, NULL), 
    ((select id from component where  "name" = 'form'), NULL, NULL),   
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'form'), NULL, NULL), 
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'container'), NULL, NULL), 
    ((select id from component where  "name" = 'table'), NULL, NULL), 
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'container'), NULL, NULL), 
    ((select id from component where  "name" = 'form'), NULL, NULL), 
    ((select id from component where  "name" = 'form'), NULL, NULL), 
    ((select id from component where  "name" = 'container'), NULL, NULL), 
    ((select id from component where  "name" = 'table'), NULL, NULL),
    ((select id from component where  "name" = 'form'), NULL, NULL), 
    ((select id from component where  "name" = 'button'), NULL, NULL), 
    ((select id from component where  "name" = 'container'), NULL, NULL), 

INSERT INTO schema_table (id_components, sort, "key", title, button, w)  VALUES
    (1, true, 'id', 'id', null, 40),
    (1, true, 'name', 'название темы', null, 120),
    (1, true, 'description', 'описание темы', null, 120),
    (1, false, 'delete', '', 2, 40),
    (1, false, 'update', '', 7, 40),
    (1, false, 'update_var', '', 19, 40),
    (9, true, 'id', 'id', null, 40),
    (9, true, 'name', 'название переменной', null, 120),
    (9, true, 'description', 'описание переменной', null, 120),
    (9, false, 'delete', '', 10, 40),
    (9, false, 'update', '', 11, 40),
    (17, true, 'id', 'id', null, 40),
    (17, true, 'name', 'название переменной', null, 120),
    (17, true, 'value', 'значение переменной', null, 120),